# Cloud Build pipeline for job-agent → Cloud Run
# Builds the Docker image from job-agent/Dockerfile, pushes to Artifact Registry,
# and deploys to Cloud Run. Designed for GitHub-triggered builds.

substitutions:
  _REGION: us-central1
  _SERVICE: job-agent
  _REPO: us-central1-docker.pkg.dev/$PROJECT_ID/containers

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_REPO/$_SERVICE:$COMMIT_SHA", "-f", "job-agent/Dockerfile", "job-agent"]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_REPO/$_SERVICE:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_REPO/$_SERVICE:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=$_REGION

images:
  - $_REPO/$_SERVICE:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
